/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: B Nazanin18.c                                         *
* Font:        B Nazanin                                             *
* Height:      18                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  18                                           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontBNazanin18;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0021[  7] = { /* code 0021, EXCLAMATION MARK */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0025[  8] = { /* code 0025, PERCENT SIGN */
  ___X____,
  X_X_____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X_X____,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0028[  8] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0029[  8] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_002A[  5] = { /* code 002A, ASTERISK */
  __X_____,
  _XXX____,
  XXXXX___,
  _XXX____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_002B[  4] = { /* code 002B, PLUS SIGN */
  _X______,
  XXX_____,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_002C[  2] = { /* code 002C, COMMA */
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_002E[  1] = { /* code 002E, FULL STOP */
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_002F[  8] = { /* code 002F, SOLIDUS */
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0030[  2] = { /* code 0030, DIGIT ZERO */
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0031[  7] = { /* code 0031, DIGIT ONE */
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0032[  7] = { /* code 0032, DIGIT TWO */
  X__X____,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0033[  7] = { /* code 0033, DIGIT THREE */
  X___X___,
  XXXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0034[  7] = { /* code 0034, DIGIT FOUR */
  X_XX____,
  XX______,
  _XXX____,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0035[  7] = { /* code 0035, DIGIT FIVE */
  ________,
  _XX_____,
  _XX_____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0036[  7] = { /* code 0036, DIGIT SIX */
  _XX_____,
  X_______,
  X__X____,
  _XXX____,
  _X______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0037[  7] = { /* code 0037, DIGIT SEVEN */
  X___X___,
  X__X____,
  _X_X____,
  _XX_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0038[  7] = { /* code 0038, DIGIT EIGHT */
  __X_____,
  __X_____,
  __X_____,
  _XX_____,
  _X_X____,
  X__X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0039[  7] = { /* code 0039, DIGIT NINE */
  _XX_____,
  X_X_____,
  X_X_____,
  XXX_____,
  __X_____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_003A[  4] = { /* code 003A, COLON */
  X_______,
  ________,
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_003D[  2] = { /* code 003D, EQUALS SIGN */
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_005B[ 10] = { /* code 005B, LEFT SQUARE BRACKET */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_005D[ 10] = { /* code 005D, RIGHT SQUARE BRACKET */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_007B[ 11] = { /* code 007B, LEFT CURLY BRACKET */
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_007D[ 11] = { /* code 007D, RIGHT CURLY BRACKET */
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_00AB[  4] = { /* code 00AB, LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
  _XXX____,
  XXX_____,
  _XX_____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_00B7[  1] = { /* code 00B7, MIDDLE DOT */
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_00BB[  4] = { /* code 00BB, RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
  X_X_____,
  _X_X____,
  _XXX____,
  X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_00D7[  4] = { /* code 00D7, MULTIPLICATION SIGN */
  X__X____,
  XXX_____,
  _XX_____,
  X_XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_00F7[  4] = { /* code 00F7, DIVISION SIGN */
  _X______,
  ________,
  XXX_____,
  _X______};

/* Start of unicode area <Spacing Modifier Letters> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_02D9[  1] = { /* code 02D9, DOT ABOVE */
  X_______};

/* Start of unicode area <Arabic (Basic and Extended)> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_060C[  2] = { /* code 060C, ARABIC COMMA */
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_061B[  4] = { /* code 061B, ARABIC SEMICOLON */
  X_______,
  X_______,
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_061F[  7] = { /* code 061F, ARABIC QUESTION MARK */
  _XX_____,
  X_X_____,
  X_______,
  _X______,
  ________,
  ________,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0621[  3] = { /* code 0621, ARABIC LETTER HAMZA */
  _X______,
  X_______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0622[  8] = { /* code 0622, ARABIC LETTER ALEF WITH MADDA ABOVE */
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0623[  9] = { /* code 0623, ARABIC LETTER ALEF WITH HAMZA ABOVE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0624[  9] = { /* code 0624, ARABIC LETTER WAW WITH HAMZA ABOVE */
  _X______,
  X_______,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0625[ 10] = { /* code 0625, ARABIC LETTER ALEF WITH HAMZA BELOW */
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0626[  6] = { /* code 0626, ARABIC LETTER YEH WITH HAMZA ABOVE */
  XX__XXX_,
  X__XX___,
  X__X____,
  X___XX__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0627[  7] = { /* code 0627, ARABIC LETTER ALEF */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0628[  5] = { /* code 0628, ARABIC LETTER BEH */
  X_____X_,
  X_____X_,
  _XXXXX__,
  ________,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0629[  6] = { /* code 0629, ARABIC LETTER TEH MARBUTA */
  _X______,
  _X______,
  ________,
  _XX_____,
  X_X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_062A[  5] = { /* code 062A, ARABIC LETTER TEH */
  __X_X___,
  ___X____,
  X_____X_,
  X_____X_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_062B[ 10] = { /* code 062B, ARABIC LETTER THEH */
  XXXXXXXX,X_______,
  ___XXX__,________,
  _X_____X,________,
  _X_____X,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_062C[  6] = { /* code 062C, ARABIC LETTER JEEM */
  XXXXX___,
  __X_____,
  XX______,
  X_XX____,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_062D[  6] = { /* code 062D, ARABIC LETTER HAH */
  XXXXX___,
  __X_____,
  XX______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_062E[  9] = { /* code 062E, ARABIC LETTER KHAH */
  __X_____,
  ________,
  ________,
  XXXXX___,
  __X_____,
  XX______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_062F[  4] = { /* code 062F, ARABIC LETTER DAL */
  _X______,
  __XX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0630[  7] = { /* code 0630, ARABIC LETTER THAL */
  _X______,
  _X______,
  ________,
  _XX_____,
  ___X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0631[  5] = { /* code 0631, ARABIC LETTER REH */
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0632[  8] = { /* code 0632, ARABIC LETTER ZAIN */
  __X_____,
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0633[ 12] = { /* code 0633, ARABIC LETTER SEEN */
  ________,_X______,
  ________,_X______,
  _____XXX,XX______,
  X____X__,________,
  X____X__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0634[ 18] = { /* code 0634, ARABIC LETTER SHEEN */
  _______X,________,
  ______XX,________,
  ________,________,
  ________,_X______,
  ________,_X______,
  _____XXX,XX______,
  X____X__,________,
  X____X__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0635[ 12] = { /* code 0635, ARABIC LETTER SAD */
  _______X,XX______,
  ______X_,_X______,
  ____XXXX,X_______,
  X___X___,________,
  X___X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0636[ 18] = { /* code 0636, ARABIC LETTER DAD */
  _______X,________,
  ________,________,
  ________,________,
  _______X,XX______,
  ______X_,_X______,
  ____XXXX,X_______,
  X___X___,________,
  X___X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0637[  7] = { /* code 0637, ARABIC LETTER TAH */
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_XXX_,
  __XX__X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0638[  7] = { /* code 0638, ARABIC LETTER ZAH */
  __X_____,
  __X__X__,
  __X_____,
  __X_____,
  __X_XXX_,
  __XX__X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0639[  7] = { /* code 0639, ARABIC LETTER AIN */
  __XX____,
  _X_X____,
  _XX_____,
  X_______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_063A[ 10] = { /* code 063A, ARABIC LETTER GHAIN */
  __X_____,
  ________,
  ________,
  __XX____,
  _X_X____,
  _XX_____,
  X_______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0640[  1] = { /* code 0640, ARABIC TATWEEL */
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0641[  7] = { /* code 0641, ARABIC LETTER FEH */
  _____X__,
  _____X__,
  _____X__,
  ____X_X_,
  X___XXX_,
  X_____X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0642[  8] = { /* code 0642, ARABIC LETTER QAF */
  ___XXX__,
  ________,
  ____X___,
  ___X_X__,
  X__XXX__,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0643[ 14] = { /* code 0643, ARABIC LETTER KAF */
  _______X,X_______,
  _____XX_,________,
  ____X___,________,
  _____X__,________,
  X_____X_,________,
  X_____X_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0644[ 10] = { /* code 0644, ARABIC LETTER LAM */
  ________,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0645[  6] = { /* code 0645, ARABIC LETTER MEEM */
  _XX_____,
  _X_X____,
  X_X_____,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0646[  7] = { /* code 0646, ARABIC LETTER NOON */
  __X_____,
  ________,
  ________,
  _____X__,
  X____X__,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0647[  3] = { /* code 0647, ARABIC LETTER HEH */
  _X______,
  X_X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0648[  6] = { /* code 0648, ARABIC LETTER WAW */
  _XX_____,
  _XX_____,
  _XX_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0649[  6] = { /* code 0649, ARABIC LETTER ALEF MAKSURA */
  ____XXX_,
  ___XX___,
  ___X____,
  X___XX__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_064A[  6] = { /* code 064A, ARABIC LETTER YEH */
  ____XXX_,
  ___XX___,
  ___X____,
  X___XX__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_064B[  3] = { /* code 064B, ARABIC FATHATAN */
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_064C[  2] = { /* code 064C, ARABIC DAMMATAN */
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_064D[  2] = { /* code 064D, ARABIC KASRATAN */
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_064E[  2] = { /* code 064E, ARABIC FATHA */
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_064F[  2] = { /* code 064F, ARABIC DAMMA */
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0650[  2] = { /* code 0650, ARABIC KASRA */
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0651[  2] = { /* code 0651, ARABIC SHADDA */
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0652[  1] = { /* code 0652, ARABIC SUKUN */
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0660[  2] = { /* code 0660, ARABIC-INDIC DIGIT ZERO */
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0661[  7] = { /* code 0661, ARABIC-INDIC DIGIT ONE */
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0662[  7] = { /* code 0662, ARABIC-INDIC DIGIT TWO */
  X__X____,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0663[  7] = { /* code 0663, ARABIC-INDIC DIGIT THREE */
  X___X___,
  XXXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0664[  7] = { /* code 0664, ARABIC-INDIC DIGIT FOUR */
  X_XX____,
  XX______,
  _XXX____,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0665[  7] = { /* code 0665, ARABIC-INDIC DIGIT FIVE */
  ________,
  _XX_____,
  _XX_____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0666[  7] = { /* code 0666, ARABIC-INDIC DIGIT SIX */
  _XX_____,
  X_______,
  X__X____,
  _XXX____,
  _X______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0667[  7] = { /* code 0667, ARABIC-INDIC DIGIT SEVEN */
  X___X___,
  X__X____,
  _X_X____,
  _XX_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0668[  7] = { /* code 0668, ARABIC-INDIC DIGIT EIGHT */
  __X_____,
  __X_____,
  __X_____,
  _XX_____,
  _X_X____,
  X__X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0669[  7] = { /* code 0669, ARABIC-INDIC DIGIT NINE */
  _XX_____,
  X_X_____,
  X_X_____,
  XXX_____,
  __X_____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_067E[  6] = { /* code 067E, ARABIC LETTER PEH */
  X_____X_,
  X_____X_,
  _XXXXX__,
  ________,
  __XXX___,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0686[  6] = { /* code 0686, ARABIC LETTER TCHEH */
  XXXXX___,
  __X_____,
  XXXX____,
  X_XX____,
  XXX_____,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_0698[  8] = { /* code 0698, ARABIC LETTER JEH */
  XXXXX___,
  __XX____,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06A9[ 14] = { /* code 06A9, ARABIC LETTER KEHEH */
  _______X,X_______,
  _____XX_,________,
  ____X___,________,
  _____X__,________,
  X_____X_,________,
  X_____X_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06AF[ 14] = { /* code 06AF, ARABIC LETTER GAF */
  _______X,X_______,
  _____XXX,X_______,
  _____XX_,________,
  _____X__,________,
  X_____X_,________,
  X_____X_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06C0[  6] = { /* code 06C0, ARABIC LETTER HEH WITH YEH ABOVE */
  _X______,
  _X______,
  ________,
  _XX_____,
  X_X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06CC[  6] = { /* code 06CC, ARABIC LETTER FARSI YEH */
  ____XXX_,
  ___XX___,
  ___X____,
  X___XX__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F0[  2] = { /* code 06F0, EXTENDED ARABIC-INDIC DIGIT ZERO */
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F1[  7] = { /* code 06F1, EXTENDED ARABIC-INDIC DIGIT ONE */
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F2[  7] = { /* code 06F2, EXTENDED ARABIC-INDIC DIGIT TWO */
  X__X____,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F3[  7] = { /* code 06F3, EXTENDED ARABIC-INDIC DIGIT THREE */
  X___X___,
  XXXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F4[  7] = { /* code 06F4, EXTENDED ARABIC-INDIC DIGIT FOUR */
  X_XX____,
  XX______,
  _XXX____,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F5[  7] = { /* code 06F5, EXTENDED ARABIC-INDIC DIGIT FIVE */
  ________,
  _XX_____,
  _XX_____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F6[  7] = { /* code 06F6, EXTENDED ARABIC-INDIC DIGIT SIX */
  _XX_____,
  X_______,
  X__X____,
  _XXX____,
  _X______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F7[  7] = { /* code 06F7, EXTENDED ARABIC-INDIC DIGIT SEVEN */
  X___X___,
  X__X____,
  _X_X____,
  _XX_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F8[  7] = { /* code 06F8, EXTENDED ARABIC-INDIC DIGIT EIGHT */
  __X_____,
  __X_____,
  __X_____,
  _XX_____,
  _X_X____,
  X__X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_06F9[  7] = { /* code 06F9, EXTENDED ARABIC-INDIC DIGIT NINE */
  _XX_____,
  X_X_____,
  X_X_____,
  XXX_____,
  __X_____,
  ___X____,
  ___X____};

/* Start of unicode area <General Punctuation> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_200C[  1] = { /* code 200C, ZERO WIDTH NON-JOINER */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_200D[  1] = { /* code 200D, ZERO WIDTH JOINER */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_200E[ 16] = { /* code 200E, LEFT-TO-RIGHT MARK */
  _XX_____,________,
  _XXX____,________,
  _X__XX__,________,
  _X____XX,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_200F[  8] = { /* code 200F, RIGHT-TO-LEFT MARK */
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_2018[  4] = { /* code 2018, LEFT SINGLE QUOTATION MARK */
  _X______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_2019[  4] = { /* code 2019, RIGHT SINGLE QUOTATION MARK */
  X_______,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_201C[  3] = { /* code 201C, LEFT DOUBLE QUOTATION MARK */
  __X_____,
  XX______,
  X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_201D[  3] = { /* code 201D, RIGHT DOUBLE QUOTATION MARK */
  X_X_____,
  X_X_____,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_2039[  5] = { /* code 2039, SINGLE LEFT-POINTING ANGLE QUOTATION MARK */
  ________,
  _X______,
  X_______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_203A[  5] = { /* code 203A, SINGLE RIGHT-POINTING ANGLE QUOTATION MARK */
  ________,
  X_______,
  _X______,
  X_______,
  ________};

/* Start of unicode area <Mathematical Operators> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_2219[  1] = { /* code 2219, BULLET OPERATOR */
  X_______};

/* Start of unicode area <Private Use Area> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E818[  4] = { /* code E818 */
  _X______,
  X_______,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E820[  2] = { /* code E820 */
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E821[  2] = { /* code E821 */
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E822[  1] = { /* code E822 */
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E823[  3] = { /* code E823 */
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E824[  2] = { /* code E824 */
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E825[  2] = { /* code E825 */
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E826[  2] = { /* code E826 */
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E827[  2] = { /* code E827 */
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E828[  4] = { /* code E828 */
  _X______,
  X_______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E829[  3] = { /* code E829 */
  XX______,
  X_______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E82A[  4] = { /* code E82A */
  _X______,
  X_______,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E82B[  4] = { /* code E82B */
  XX______,
  X_______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E82C[  3] = { /* code E82C */
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_E82D[  4] = { /* code E82D */
  _X______,
  XX______,
  X_______,
  X_______};

/* Start of unicode area <Arabic Presentation Forms-A> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB56[  6] = { /* code FB56, ARABIC LETTER PEH ISOLATED FORM */
  X_____X_,
  X_____X_,
  _XXXXX__,
  ________,
  __XXX___,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB57[  6] = { /* code FB57, ARABIC LETTER PEH FINAL FORM */
  X_______,
  X_____X_,
  _XXXXX_X,
  ________,
  __XXX___,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB58[  6] = { /* code FB58, ARABIC LETTER PEH INITIAL FORM */
  _X______,
  _X______,
  XX______,
  ________,
  XXX_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB59[  5] = { /* code FB59, ARABIC LETTER PEH MEDIAL FORM */
  ________,
  XXXX____,
  ________,
  XXX_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB7A[  6] = { /* code FB7A, ARABIC LETTER TCHEH ISOLATED FORM */
  XXXXX___,
  __X_____,
  XXXX____,
  X_XX____,
  XXX_____,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB7B[  6] = { /* code FB7B, ARABIC LETTER TCHEH FINAL FORM */
  XXXXX___,
  _X_X____,
  XX_XX___,
  X_X_____,
  XXX_____,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB7C[  7] = { /* code FB7C, ARABIC LETTER TCHEH INITIAL FORM */
  _XX_____,
  ___X____,
  ___XXX__,
  XXX_____,
  ________,
  __XX____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB7D[  7] = { /* code FB7D, ARABIC LETTER TCHEH MEDIAL FORM */
  _XX_____,
  ___XXX__,
  __XXX___,
  XX___XX_,
  ________,
  __XXX___,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB8A[  8] = { /* code FB8A, ARABIC LETTER JEH ISOLATED FORM */
  XXXXX___,
  __XX____,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB8B[  8] = { /* code FB8B, ARABIC LETTER JEH FINAL FORM */
  XXXXX___,
  __XX____,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB8E[ 14] = { /* code FB8E, ARABIC LETTER KEHEH ISOLATED FORM */
  _______X,X_______,
  _____XX_,________,
  ____X___,________,
  _____X__,________,
  X_____X_,________,
  X_____X_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB8F[ 14] = { /* code FB8F, ARABIC LETTER KEHEH FINAL FORM */
  _______X,X_______,
  _____XXX,________,
  ____X___,________,
  _____X__,________,
  X_____X_,________,
  X_____XX,________,
  _XXXXX__,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB90[  7] = { /* code FB90, ARABIC LETTER KEHEH INITIAL FORM */
  ___XX___,
  _XX_____,
  X_______,
  _X______,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB91[  7] = { /* code FB91, ARABIC LETTER KEHEH MEDIAL FORM */
  ___XX___,
  _XXX____,
  X_______,
  _X______,
  __X_____,
  __XX____,
  XX__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB92[ 14] = { /* code FB92, ARABIC LETTER GAF ISOLATED FORM */
  _______X,X_______,
  _____XXX,X_______,
  _____XX_,________,
  _____X__,________,
  X_____X_,________,
  X_____X_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB93[ 14] = { /* code FB93, ARABIC LETTER GAF FINAL FORM */
  _______X,________,
  _____XXX,X_______,
  ____XXX_,________,
  _____X__,________,
  X_____X_,________,
  X_____XX,________,
  _XXXXX__,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB94[  7] = { /* code FB94, ARABIC LETTER GAF INITIAL FORM */
  ___X____,
  _XXXX___,
  _XX_____,
  _X______,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FB95[  7] = { /* code FB95, ARABIC LETTER GAF MEDIAL FORM */
  ___X____,
  _XXXX___,
  XXX_____,
  _X______,
  __X_____,
  __XX____,
  XX__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FBA4[  6] = { /* code FBA4, ARABIC LETTER HEH WITH YEH ABOVE ISOLATED FORM */
  _X______,
  _X______,
  ________,
  _XX_____,
  X_X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FBA5[  7] = { /* code FBA5, ARABIC LETTER HEH WITH YEH ABOVE FINAL FORM */
  _X______,
  _XX_____,
  _X______,
  __X_____,
  XXX_____,
  XXX_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FBFC[  6] = { /* code FBFC, ARABIC LETTER FARSI YEH ISOLATED FORM */
  ____XXX_,
  ___XX___,
  ___X____,
  X___XX__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FBFD[  4] = { /* code FBFD, ARABIC LETTER FARSI YEH FINAL FORM */
  ____XXX_,
  X__X____,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FBFE[  5] = { /* code FBFE, ARABIC LETTER FARSI YEH INITIAL FORM */
  _X______,
  _X______,
  XX______,
  ________,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FBFF[  4] = { /* code FBFF, ARABIC LETTER FARSI YEH MEDIAL FORM */
  ________,
  XXXX____,
  ________,
  XXX_____};

/* Start of unicode area <Arabic Presentation Forms-A> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FC5E[  4] = { /* code FC5E, ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM */
  XX______,
  X_______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FC5F[  4] = { /* code FC5F, ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM */
  _X______,
  XX______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FC60[  4] = { /* code FC60, ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM */
  _X______,
  X_______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FC61[  3] = { /* code FC61, ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM */
  XX______,
  X_______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FC62[  3] = { /* code FC62, ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM */
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FDF2[  8] = { /* code FDF2, ARABIC LIGATURE ALLAH ISOLATED FORM */
  ____X___,
  ________,
  ____XX__,
  ____X_X_,
  __X_X_X_,
  XXX_X_X_,
  XXX_X_X_,
  __XX_XX_};

/* Start of unicode area <Arabic Presentation Forms-B> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE81[  8] = { /* code FE81, ARABIC LETTER ALEF WITH MADDA ABOVE ISOLATED FORM */
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE82[  8] = { /* code FE82, ARABIC LETTER ALEF WITH MADDA ABOVE FINAL FORM */
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE83[  9] = { /* code FE83, ARABIC LETTER ALEF WITH HAMZA ABOVE ISOLATED FORM */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE84[  9] = { /* code FE84, ARABIC LETTER ALEF WITH HAMZA ABOVE FINAL FORM */
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE85[  9] = { /* code FE85, ARABIC LETTER WAW WITH HAMZA ABOVE ISOLATED FORM */
  _X______,
  X_______,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE86[  9] = { /* code FE86, ARABIC LETTER WAW WITH HAMZA ABOVE FINAL FORM */
  _X______,
  X_______,
  XX______,
  _XX_____,
  _XX_____,
  _XXX____,
  __X_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE87[ 10] = { /* code FE87, ARABIC LETTER ALEF WITH HAMZA BELOW ISOLATED FORM */
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE88[ 10] = { /* code FE88, ARABIC LETTER ALEF WITH HAMZA BELOW FINAL FORM */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XX______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE89[  6] = { /* code FE89, ARABIC LETTER YEH WITH HAMZA ABOVE ISOLATED FORM */
  XX__XXX_,
  X__XX___,
  X__X____,
  X___XX__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE8A[  7] = { /* code FE8A, ARABIC LETTER YEH WITH HAMZA ABOVE FINAL FORM */
  XX______,
  XX______,
  ________,
  ____XXX_,
  X__X____,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE8B[  6] = { /* code FE8B, ARABIC LETTER YEH WITH HAMZA ABOVE INITIAL FORM */
  _X______,
  _X______,
  ________,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE8C[  5] = { /* code FE8C, ARABIC LETTER YEH WITH HAMZA ABOVE MEDIAL FORM */
  _X______,
  _XX_____,
  ________,
  ________,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE8D[  7] = { /* code FE8D, ARABIC LETTER ALEF ISOLATED FORM */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE8E[  7] = { /* code FE8E, ARABIC LETTER ALEF FINAL FORM */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE8F[  5] = { /* code FE8F, ARABIC LETTER BEH ISOLATED FORM */
  X_____X_,
  X_____X_,
  _XXXXX__,
  ________,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE90[  5] = { /* code FE90, ARABIC LETTER BEH FINAL FORM */
  X_______,
  X_____X_,
  _XXXXX_X,
  ________,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE91[  5] = { /* code FE91, ARABIC LETTER BEH INITIAL FORM */
  _X______,
  _X______,
  XX______,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE92[  4] = { /* code FE92, ARABIC LETTER BEH MEDIAL FORM */
  ________,
  XXXX____,
  ________,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE93[  6] = { /* code FE93, ARABIC LETTER TEH MARBUTA ISOLATED FORM */
  _X______,
  _X______,
  ________,
  _XX_____,
  X_X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE94[  7] = { /* code FE94, ARABIC LETTER TEH MARBUTA FINAL FORM */
  _X______,
  _XX_____,
  _X______,
  __X_____,
  XXX_____,
  XXX_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE95[  5] = { /* code FE95, ARABIC LETTER TEH ISOLATED FORM */
  __X_X___,
  ___X____,
  X_____X_,
  X_____X_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE96[  5] = { /* code FE96, ARABIC LETTER TEH FINAL FORM */
  __X_X___,
  ___X____,
  X_______,
  X_____X_,
  _XXXXX_X};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE97[  5] = { /* code FE97, ARABIC LETTER TEH INITIAL FORM */
  XXXX____,
  ________,
  __X_____,
  __X_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE98[  5] = { /* code FE98, ARABIC LETTER TEH MEDIAL FORM */
  X_X_____,
  _X______,
  ________,
  ________,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE99[ 10] = { /* code FE99, ARABIC LETTER THEH ISOLATED FORM */
  XXXXXXXX,X_______,
  ___XXX__,________,
  _X_____X,________,
  _X_____X,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE9A[ 10] = { /* code FE9A, ARABIC LETTER THEH FINAL FORM */
  XXXXXXXX,X_______,
  _____X__,________,
  _X______,________,
  _X_____X,________,
  __XXXXX_,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE9B[  6] = { /* code FE9B, ARABIC LETTER THEH INITIAL FORM */
  XXX_____,
  XXX_____,
  ________,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE9C[ 10] = { /* code FE9C, ARABIC LETTER THEH MEDIAL FORM */
  XXXXXXXX,X_______,
  _____X__,________,
  ________,________,
  ________,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE9D[  6] = { /* code FE9D, ARABIC LETTER JEEM ISOLATED FORM */
  XXXXX___,
  __X_____,
  XX______,
  X_XX____,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE9E[  6] = { /* code FE9E, ARABIC LETTER JEEM FINAL FORM */
  XXXXX___,
  _X_X____,
  X__XX___,
  X_X_____,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FE9F[  6] = { /* code FE9F, ARABIC LETTER JEEM INITIAL FORM */
  _XX_____,
  ___X____,
  ___XXX__,
  XXX_____,
  ________,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA0[  6] = { /* code FEA0, ARABIC LETTER JEEM MEDIAL FORM */
  _XX_____,
  ___XXX__,
  __XXX___,
  XX___XX_,
  ________,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA1[  6] = { /* code FEA1, ARABIC LETTER HAH ISOLATED FORM */
  XXXXX___,
  __X_____,
  XX______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA2[  6] = { /* code FEA2, ARABIC LETTER HAH FINAL FORM */
  XXXXX___,
  _X_X____,
  X__XX___,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA3[  4] = { /* code FEA3, ARABIC LETTER HAH INITIAL FORM */
  _XX_____,
  ___X____,
  ___XXX__,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA4[  4] = { /* code FEA4, ARABIC LETTER HAH MEDIAL FORM */
  _XX_____,
  ___XXX__,
  __XXX___,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA5[  9] = { /* code FEA5, ARABIC LETTER KHAH ISOLATED FORM */
  __X_____,
  ________,
  ________,
  XXXXX___,
  __X_____,
  XX______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA6[  9] = { /* code FEA6, ARABIC LETTER KHAH FINAL FORM */
  __X_____,
  ________,
  ________,
  XXXXX___,
  _X_X____,
  X__XX___,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA7[  6] = { /* code FEA7, ARABIC LETTER KHAH INITIAL FORM */
  ___X____,
  ________,
  _XXX____,
  ___XXX__,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA8[  6] = { /* code FEA8, ARABIC LETTER KHAH MEDIAL FORM */
  ___X____,
  ________,
  _XX_____,
  ___XXX__,
  __XXX___,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEA9[  4] = { /* code FEA9, ARABIC LETTER DAL ISOLATED FORM */
  _X______,
  __XX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEAA[  5] = { /* code FEAA, ARABIC LETTER DAL FINAL FORM */
  __X_____,
  __X_____,
  ___X____,
  X__X____,
  XXX_X___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEAB[  7] = { /* code FEAB, ARABIC LETTER THAL ISOLATED FORM */
  _X______,
  _X______,
  ________,
  _XX_____,
  ___X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEAC[  7] = { /* code FEAC, ARABIC LETTER THAL FINAL FORM */
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  X__X____,
  XXX_X___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEAD[  5] = { /* code FEAD, ARABIC LETTER REH ISOLATED FORM */
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEAE[  5] = { /* code FEAE, ARABIC LETTER REH FINAL FORM */
  ________,
  __X_____,
  __X_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEAF[  8] = { /* code FEAF, ARABIC LETTER ZAIN ISOLATED FORM */
  __X_____,
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB0[  8] = { /* code FEB0, ARABIC LETTER ZAIN FINAL FORM */
  __X_____,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB1[ 12] = { /* code FEB1, ARABIC LETTER SEEN ISOLATED FORM */
  ________,_X______,
  ________,_X______,
  _____XXX,XX______,
  X____X__,________,
  X____X__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB2[ 10] = { /* code FEB2, ARABIC LETTER SEEN FINAL FORM */
  ________,________,
  _____XXX,XXX_____,
  X___X___,________,
  X___X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB3[  3] = { /* code FEB3, ARABIC LETTER SEEN INITIAL FORM */
  _____X__,
  _X_X_X__,
  X_X_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB4[  2] = { /* code FEB4, ARABIC LETTER SEEN MEDIAL FORM */
  _X______,
  X_XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB5[ 18] = { /* code FEB5, ARABIC LETTER SHEEN ISOLATED FORM */
  _______X,________,
  ______XX,________,
  ________,________,
  ________,_X______,
  ________,_X______,
  _____XXX,XX______,
  X____X__,________,
  X____X__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB6[ 18] = { /* code FEB6, ARABIC LETTER SHEEN FINAL FORM */
  ________,________,
  ______X_,________,
  ______XX,________,
  ________,________,
  ________,________,
  _____XXX,XXX_____,
  X___X___,________,
  X___X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB7[  6] = { /* code FEB7, ARABIC LETTER SHEEN INITIAL FORM */
  ___X____,
  ___XX___,
  ________,
  _____X__,
  _X_X_X__,
  X_X_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB8[  6] = { /* code FEB8, ARABIC LETTER SHEEN MEDIAL FORM */
  ________,
  ___X____,
  ___XX___,
  ________,
  _X______,
  X_XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEB9[ 12] = { /* code FEB9, ARABIC LETTER SAD ISOLATED FORM */
  _______X,XX______,
  ______X_,_X______,
  ____XXXX,X_______,
  X___X___,________,
  X___X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEBA[ 12] = { /* code FEBA, ARABIC LETTER SAD FINAL FORM */
  _______X,XX______,
  ______X_,_X______,
  _____XXX,XXX_____,
  X____X__,________,
  X___XX__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEBB[  3] = { /* code FEBB, ARABIC LETTER SAD INITIAL FORM */
  ____XXX_,
  _X_X__X_,
  X_XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEBC[  3] = { /* code FEBC, ARABIC LETTER SAD MEDIAL FORM */
  ____XXX_,
  _X_X__X_,
  X_XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEBD[ 18] = { /* code FEBD, ARABIC LETTER DAD ISOLATED FORM */
  _______X,________,
  ________,________,
  ________,________,
  _______X,XX______,
  ______X_,_X______,
  ____XXXX,X_______,
  X___X___,________,
  X___X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEBE[ 18] = { /* code FEBE, ARABIC LETTER DAD FINAL FORM */
  _______X,________,
  ________,________,
  ________,________,
  _______X,XX______,
  ______X_,_X______,
  _____XXX,XXX_____,
  X____X__,________,
  X___XX__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEBF[  6] = { /* code FEBF, ARABIC LETTER DAD INITIAL FORM */
  ____X___,
  ____X___,
  ________,
  ____XXX_,
  _X_X__X_,
  X_XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC0[  6] = { /* code FEC0, ARABIC LETTER DAD MEDIAL FORM */
  ____X___,
  ____X___,
  ________,
  ____XXX_,
  _X_X__X_,
  X_XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC1[  7] = { /* code FEC1, ARABIC LETTER TAH ISOLATED FORM */
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_XXX_,
  __XX__X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC2[  7] = { /* code FEC2, ARABIC LETTER TAH FINAL FORM */
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_XXX_,
  __XX__X_,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC3[  7] = { /* code FEC3, ARABIC LETTER TAH INITIAL FORM */
  _X______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX__X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC4[  7] = { /* code FEC4, ARABIC LETTER TAH MEDIAL FORM */
  _X______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX__X__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC5[  7] = { /* code FEC5, ARABIC LETTER ZAH ISOLATED FORM */
  __X_____,
  __X__X__,
  __X_____,
  __X_____,
  __X_XXX_,
  __XX__X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC6[  7] = { /* code FEC6, ARABIC LETTER ZAH FINAL FORM */
  __X_____,
  __X__X__,
  __X_____,
  __X_____,
  __X_XXX_,
  __XX__X_,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC7[  7] = { /* code FEC7, ARABIC LETTER ZAH INITIAL FORM */
  _X______,
  _X__X___,
  _X______,
  _X______,
  _X_XXX__,
  _XX__X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC8[  7] = { /* code FEC8, ARABIC LETTER ZAH MEDIAL FORM */
  _X______,
  _X__X___,
  _X______,
  _X______,
  _X_XXX__,
  _XX__X__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEC9[  7] = { /* code FEC9, ARABIC LETTER AIN ISOLATED FORM */
  __XX____,
  _X_X____,
  _XX_____,
  X_______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FECA[  6] = { /* code FECA, ARABIC LETTER AIN FINAL FORM */
  _XXX____,
  _XX_____,
  X__XX___,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FECB[  4] = { /* code FECB, ARABIC LETTER AIN INITIAL FORM */
  __X_____,
  _X______,
  _X______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FECC[  3] = { /* code FECC, ARABIC LETTER AIN MEDIAL FORM */
  _XX_____,
  __X_____,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FECD[ 10] = { /* code FECD, ARABIC LETTER GHAIN ISOLATED FORM */
  __X_____,
  ________,
  ________,
  __XX____,
  _X_X____,
  _XX_____,
  X_______,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FECE[  9] = { /* code FECE, ARABIC LETTER GHAIN FINAL FORM */
  __X_____,
  ________,
  ________,
  _XXX____,
  _XX_____,
  X__XX___,
  X_______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FECF[  7] = { /* code FECF, ARABIC LETTER GHAIN INITIAL FORM */
  __X_____,
  __X_____,
  ________,
  __X_____,
  _X______,
  _X______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED0[  6] = { /* code FED0, ARABIC LETTER GHAIN MEDIAL FORM */
  __X_____,
  ________,
  ________,
  _XX_____,
  __X_____,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED1[  7] = { /* code FED1, ARABIC LETTER FEH ISOLATED FORM */
  _____X__,
  _____X__,
  _____X__,
  ____X_X_,
  X___XXX_,
  X_____X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED2[  6] = { /* code FED2, ARABIC LETTER FEH FINAL FORM */
  _____XX_,
  ________,
  _____XX_,
  X___X_X_,
  X___X_X_,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED3[  7] = { /* code FED3, ARABIC LETTER FEH INITIAL FORM */
  _X______,
  _X______,
  _XX_____,
  _XX_____,
  _XX_____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED4[  6] = { /* code FED4, ARABIC LETTER FEH MEDIAL FORM */
  _XX_____,
  ________,
  __XX____,
  _X_X____,
  _X_X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED5[  8] = { /* code FED5, ARABIC LETTER QAF ISOLATED FORM */
  ___XXX__,
  ________,
  ____X___,
  ___X_X__,
  X__XXX__,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED6[  8] = { /* code FED6, ARABIC LETTER QAF FINAL FORM */
  ___XXX__,
  ________,
  ___XX___,
  ___XX___,
  X__XXX__,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED7[  7] = { /* code FED7, ARABIC LETTER QAF INITIAL FORM */
  _XX_____,
  X_X_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED8[  6] = { /* code FED8, ARABIC LETTER QAF MEDIAL FORM */
  _XXX____,
  ________,
  __XX____,
  _X_X____,
  _X_X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FED9[ 14] = { /* code FED9, ARABIC LETTER KAF ISOLATED FORM */
  _______X,X_______,
  _____XX_,________,
  ____X___,________,
  _____X__,________,
  X_____X_,________,
  X_____X_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEDA[ 14] = { /* code FEDA, ARABIC LETTER KAF FINAL FORM */
  _______X,X_______,
  _____XXX,________,
  ____X___,________,
  _____X__,________,
  X_____X_,________,
  X_____XX,________,
  _XXXXX__,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEDB[  7] = { /* code FEDB, ARABIC LETTER KAF INITIAL FORM */
  ___XX___,
  _XX_____,
  X_______,
  _X______,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEDC[  7] = { /* code FEDC, ARABIC LETTER KAF MEDIAL FORM */
  ___XX___,
  _XXX____,
  X_______,
  _X______,
  __X_____,
  __XX____,
  XX__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEDD[ 10] = { /* code FEDD, ARABIC LETTER LAM ISOLATED FORM */
  ________,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEDE[ 10] = { /* code FEDE, ARABIC LETTER LAM FINAL FORM */
  ________,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  X__X____,
  X__X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEDF[  7] = { /* code FEDF, ARABIC LETTER LAM INITIAL FORM */
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE0[  7] = { /* code FEE0, ARABIC LETTER LAM MEDIAL FORM */
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE1[  6] = { /* code FEE1, ARABIC LETTER MEEM ISOLATED FORM */
  _XX_____,
  _X_X____,
  X_X_____,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE2[  5] = { /* code FEE2, ARABIC LETTER MEEM FINAL FORM */
  _XX_____,
  XX_XX___,
  X_XXX___,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE3[  3] = { /* code FEE3, ARABIC LETTER MEEM INITIAL FORM */
  __XX____,
  _X_X____,
  X_XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE4[  3] = { /* code FEE4, ARABIC LETTER MEEM MEDIAL FORM */
  __XX____,
  _X_X____,
  X_XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE5[  7] = { /* code FEE5, ARABIC LETTER NOON ISOLATED FORM */
  __X_____,
  ________,
  ________,
  _____X__,
  X____X__,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE6[  7] = { /* code FEE6, ARABIC LETTER NOON FINAL FORM */
  __X_____,
  ________,
  ________,
  _____XX_,
  X____X__,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE7[  6] = { /* code FEE7, ARABIC LETTER NOON INITIAL FORM */
  _X______,
  _X______,
  ________,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE8[  4] = { /* code FEE8, ARABIC LETTER NOON MEDIAL FORM */
  XXXXX___,
  ________,
  ________,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEE9[  3] = { /* code FEE9, ARABIC LETTER HEH ISOLATED FORM */
  _X______,
  X_X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEEA[  5] = { /* code FEEA, ARABIC LETTER HEH FINAL FORM */
  ________,
  __X_____,
  XXX_____,
  XXX_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEEB[  4] = { /* code FEEB, ARABIC LETTER HEH INITIAL FORM */
  _XX_____,
  _XXX____,
  _XX_X___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEEC[  7] = { /* code FEEC, ARABIC LETTER HEH MEDIAL FORM */
  __X_____,
  _XX_____,
  X_X_____,
  XXXXX___,
  _XX_____,
  __X_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEED[  6] = { /* code FEED, ARABIC LETTER WAW ISOLATED FORM */
  _XX_____,
  _XX_____,
  _XX_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEEE[  6] = { /* code FEEE, ARABIC LETTER WAW FINAL FORM */
  _XX_____,
  _XX_____,
  _XXX____,
  __X_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEEF[  6] = { /* code FEEF, ARABIC LETTER ALEF MAKSURA ISOLATED FORM */
  ____XXX_,
  ___XX___,
  ___X____,
  X___XX__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF0[  4] = { /* code FEF0, ARABIC LETTER ALEF MAKSURA FINAL FORM */
  ____XXX_,
  X__X____,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF1[  6] = { /* code FEF1, ARABIC LETTER YEH ISOLATED FORM */
  ____XXX_,
  ___XX___,
  ___X____,
  X___XX__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF2[  4] = { /* code FEF2, ARABIC LETTER YEH FINAL FORM */
  ____XXX_,
  X__X____,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF3[  5] = { /* code FEF3, ARABIC LETTER YEH INITIAL FORM */
  _X______,
  _X______,
  XX______,
  ________,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF4[  4] = { /* code FEF4, ARABIC LETTER YEH MEDIAL FORM */
  ________,
  XXXX____,
  ________,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF5[  8] = { /* code FEF5, ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM */
  XX______,
  _____X__,
  _X___X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ____X___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF6[  9] = { /* code FEF6, ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM */
  XX______,
  _____X__,
  _X___X__,
  _XX__X__,
  __X__X__,
  ___X_X__,
  ____XX__,
  ___X_X__,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF7[  9] = { /* code FEF7, ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM */
  X_______,
  X_______,
  ________,
  XX__X___,
  _XX_X___,
  __X_X___,
  ___XX___,
  ___XX___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF8[ 10] = { /* code FEF8, ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM */
  X_______,
  X_______,
  _____X__,
  X____X__,
  _XX__X__,
  __X__X__,
  ___X_X__,
  ____XX__,
  ___X_X__,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEF9[ 10] = { /* code FEF9, ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW ISOLATED FORM */
  ____X___,
  X___X___,
  _X__X___,
  __X_X___,
  ___X____,
  ___X____,
  __XX____,
  _X______,
  XX______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEFA[ 10] = { /* code FEFA, ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW FINAL FORM */
  ________,
  X___X___,
  _X__X___,
  __X_X___,
  __X_X___,
  ___XX___,
  __XXX___,
  XX______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEFB[  7] = { /* code FEFB, ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM */
  ____X___,
  X___X___,
  _X__X___,
  __X_X___,
  ___X____,
  ___X____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FEFC[  8] = { /* code FEFC, ARABIC LIGATURE LAM WITH ALEF FINAL FORM */
  ________,
  X___X___,
  _X__X___,
  __X_X___,
  __X_X___,
  ___XX___,
  ___XX___,
  _XX_____};

/* Start of unicode area <Special> */
GUI_CONST_STORAGE unsigned char acGUI_FontBNazanin18_FFFF[  8] = { /* code FFFF */
  XXXXX___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  XXXXX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontBNazanin18_CharInfo[289] = {
   {   1,   1,   0,  12,   3, acGUI_FontBNazanin18_0020 } /* code 0020, SPACE */
  ,{   1,   7,   1,   5,   2, acGUI_FontBNazanin18_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   4,   8,   0,   5,   5, acGUI_FontBNazanin18_0025 } /* code 0025, PERCENT SIGN */
  ,{   2,   8,   1,   6,   3, acGUI_FontBNazanin18_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   2,   8,   1,   6,   3, acGUI_FontBNazanin18_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   5,   5,   1,   7,   6, acGUI_FontBNazanin18_002A } /* code 002A, ASTERISK */
  ,{   3,   4,   1,   8,   4, acGUI_FontBNazanin18_002B } /* code 002B, PLUS SIGN */
  ,{   2,   2,   1,  11,   2, acGUI_FontBNazanin18_002C } /* code 002C, COMMA */
  ,{   4,   1,   0,   9,   4, acGUI_FontBNazanin18_002D } /* code 002D, HYPHEN-MINUS */
  ,{   1,   1,   1,  11,   2, acGUI_FontBNazanin18_002E } /* code 002E, FULL STOP */
  ,{   3,   8,  -1,   5,   2, acGUI_FontBNazanin18_002F } /* code 002F, SOLIDUS */
  ,{   1,   2,   2,   8,   6, acGUI_FontBNazanin18_0030 } /* code 0030, DIGIT ZERO */
  ,{   2,   7,   2,   5,   6, acGUI_FontBNazanin18_0031 } /* code 0031, DIGIT ONE */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_0032 } /* code 0032, DIGIT TWO */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_0033 } /* code 0033, DIGIT THREE */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_0034 } /* code 0034, DIGIT FOUR */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_0035 } /* code 0035, DIGIT FIVE */
  ,{   4,   7,   0,   5,   5, acGUI_FontBNazanin18_0036 } /* code 0036, DIGIT SIX */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_0037 } /* code 0037, DIGIT SEVEN */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_0038 } /* code 0038, DIGIT EIGHT */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_0039 } /* code 0039, DIGIT NINE */
  ,{   1,   4,   1,   8,   2, acGUI_FontBNazanin18_003A } /* code 003A, COLON */
  ,{   4,   2,   0,   9,   4, acGUI_FontBNazanin18_003D } /* code 003D, EQUALS SIGN */
  ,{   1,  10,   1,   3,   4, acGUI_FontBNazanin18_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   1,  10,   1,   3,   4, acGUI_FontBNazanin18_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   3,  11,   1,   3,   6, acGUI_FontBNazanin18_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   3,  11,   1,   3,   6, acGUI_FontBNazanin18_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   4,   4,   0,   7,   5, acGUI_FontBNazanin18_00AB } /* code 00AB, LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
  ,{   1,   1,   0,   7,   2, acGUI_FontBNazanin18_00B7 } /* code 00B7, MIDDLE DOT */
  ,{   4,   4,   0,   7,   5, acGUI_FontBNazanin18_00BB } /* code 00BB, RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
  ,{   4,   4,   0,   8,   4, acGUI_FontBNazanin18_00D7 } /* code 00D7, MULTIPLICATION SIGN */
  ,{   3,   4,   1,   7,   6, acGUI_FontBNazanin18_00F7 } /* code 00F7, DIVISION SIGN */
  ,{   1,   1,   0,   7,   2, acGUI_FontBNazanin18_02D9 } /* code 02D9, DOT ABOVE */
  ,{   1,   2,   1,  10,   2, acGUI_FontBNazanin18_060C } /* code 060C, ARABIC COMMA */
  ,{   1,   4,   1,   8,   2, acGUI_FontBNazanin18_061B } /* code 061B, ARABIC SEMICOLON */
  ,{   3,   7,   1,   5,   4, acGUI_FontBNazanin18_061F } /* code 061F, ARABIC QUESTION MARK */
  ,{   3,   3,   1,   9,   4, acGUI_FontBNazanin18_0621 } /* code 0621, ARABIC LETTER HAMZA */
  ,{   2,   8,   0,   4,   3, acGUI_FontBNazanin18_0622 } /* code 0622, ARABIC LETTER ALEF WITH MADDA ABOVE */
  ,{   2,   9,   1,   3,   3, acGUI_FontBNazanin18_0623 } /* code 0623, ARABIC LETTER ALEF WITH HAMZA ABOVE */
  ,{   3,   9,   0,   6,   4, acGUI_FontBNazanin18_0624 } /* code 0624, ARABIC LETTER WAW WITH HAMZA ABOVE */
  ,{   2,  10,   1,   5,   3, acGUI_FontBNazanin18_0625 } /* code 0625, ARABIC LETTER ALEF WITH HAMZA BELOW */
  ,{   7,   6,   1,   8,   8, acGUI_FontBNazanin18_0626 } /* code 0626, ARABIC LETTER YEH WITH HAMZA ABOVE */
  ,{   1,   7,   1,   5,   2, acGUI_FontBNazanin18_0627 } /* code 0627, ARABIC LETTER ALEF */
  ,{   7,   5,   1,   9,   8, acGUI_FontBNazanin18_0628 } /* code 0628, ARABIC LETTER BEH */
  ,{   3,   6,   1,   6,   4, acGUI_FontBNazanin18_0629 } /* code 0629, ARABIC LETTER TEH MARBUTA */
  ,{   7,   5,   1,   7,   8, acGUI_FontBNazanin18_062A } /* code 062A, ARABIC LETTER TEH */
  ,{   9,   5,   0,   7,   8, acGUI_FontBNazanin18_062B } /* code 062B, ARABIC LETTER THEH */
  ,{   6,   6,   1,   9,   6, acGUI_FontBNazanin18_062C } /* code 062C, ARABIC LETTER JEEM */
  ,{   6,   6,   1,   9,   6, acGUI_FontBNazanin18_062D } /* code 062D, ARABIC LETTER HAH */
  ,{   6,   9,   1,   6,   6, acGUI_FontBNazanin18_062E } /* code 062E, ARABIC LETTER KHAH */
  ,{   4,   4,   1,   8,   5, acGUI_FontBNazanin18_062F } /* code 062F, ARABIC LETTER DAL */
  ,{   4,   7,   1,   5,   5, acGUI_FontBNazanin18_0630 } /* code 0630, ARABIC LETTER THAL */
  ,{   3,   5,   0,  10,   4, acGUI_FontBNazanin18_0631 } /* code 0631, ARABIC LETTER REH */
  ,{   3,   8,   0,   7,   4, acGUI_FontBNazanin18_0632 } /* code 0632, ARABIC LETTER ZAIN */
  ,{  10,   6,   1,   9,  10, acGUI_FontBNazanin18_0633 } /* code 0633, ARABIC LETTER SEEN */
  ,{  10,   9,   1,   6,  10, acGUI_FontBNazanin18_0634 } /* code 0634, ARABIC LETTER SHEEN */
  ,{  10,   6,   1,   9,  11, acGUI_FontBNazanin18_0635 } /* code 0635, ARABIC LETTER SAD */
  ,{  10,   9,   1,   6,  11, acGUI_FontBNazanin18_0636 } /* code 0636, ARABIC LETTER DAD */
  ,{   7,   7,   1,   5,   8, acGUI_FontBNazanin18_0637 } /* code 0637, ARABIC LETTER TAH */
  ,{   7,   7,   1,   5,   8, acGUI_FontBNazanin18_0638 } /* code 0638, ARABIC LETTER ZAH */
  ,{   5,   7,   1,   8,   5, acGUI_FontBNazanin18_0639 } /* code 0639, ARABIC LETTER AIN */
  ,{   5,  10,   1,   5,   5, acGUI_FontBNazanin18_063A } /* code 063A, ARABIC LETTER GHAIN */
  ,{   4,   1,   0,  11,   4, acGUI_FontBNazanin18_0640 } /* code 0640, ARABIC TATWEEL */
  ,{   7,   7,   1,   5,   8, acGUI_FontBNazanin18_0641 } /* code 0641, ARABIC LETTER FEH */
  ,{   6,   8,   1,   7,   7, acGUI_FontBNazanin18_0642 } /* code 0642, ARABIC LETTER QAF */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_0643 } /* code 0643, ARABIC LETTER KAF */
  ,{   6,  10,   1,   5,   6, acGUI_FontBNazanin18_0644 } /* code 0644, ARABIC LETTER LAM */
  ,{   4,   6,   1,   9,   5, acGUI_FontBNazanin18_0645 } /* code 0645, ARABIC LETTER MEEM */
  ,{   6,   7,   1,   8,   7, acGUI_FontBNazanin18_0646 } /* code 0646, ARABIC LETTER NOON */
  ,{   3,   3,   1,   9,   4, acGUI_FontBNazanin18_0647 } /* code 0647, ARABIC LETTER HEH */
  ,{   3,   6,   0,   9,   4, acGUI_FontBNazanin18_0648 } /* code 0648, ARABIC LETTER WAW */
  ,{   7,   6,   1,   8,   8, acGUI_FontBNazanin18_0649 } /* code 0649, ARABIC LETTER ALEF MAKSURA */
  ,{   7,   6,   1,   8,   8, acGUI_FontBNazanin18_064A } /* code 064A, ARABIC LETTER YEH */
  ,{   1,   3,   0,   2,   0, acGUI_FontBNazanin18_064B } /* code 064B, ARABIC FATHATAN */
  ,{   2,   2,   0,   3,   0, acGUI_FontBNazanin18_064C } /* code 064C, ARABIC DAMMATAN */
  ,{   2,   2,   1,  16,   0, acGUI_FontBNazanin18_064D } /* code 064D, ARABIC KASRATAN */
  ,{   2,   2,   0,   3,   0, acGUI_FontBNazanin18_064E } /* code 064E, ARABIC FATHA */
  ,{   2,   2,   0,   3,   0, acGUI_FontBNazanin18_064F } /* code 064F, ARABIC DAMMA */
  ,{   2,   2,   1,  16,   0, acGUI_FontBNazanin18_0650 } /* code 0650, ARABIC KASRA */
  ,{   2,   2,   0,   3,   0, acGUI_FontBNazanin18_0651 } /* code 0651, ARABIC SHADDA */
  ,{   1,   1,   1,   3,   0, acGUI_FontBNazanin18_0652 } /* code 0652, ARABIC SUKUN */
  ,{   1,   2,   2,   8,   6, acGUI_FontBNazanin18_0660 } /* code 0660, ARABIC-INDIC DIGIT ZERO */
  ,{   2,   7,   2,   5,   6, acGUI_FontBNazanin18_0661 } /* code 0661, ARABIC-INDIC DIGIT ONE */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_0662 } /* code 0662, ARABIC-INDIC DIGIT TWO */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_0663 } /* code 0663, ARABIC-INDIC DIGIT THREE */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_0664 } /* code 0664, ARABIC-INDIC DIGIT FOUR */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_0665 } /* code 0665, ARABIC-INDIC DIGIT FIVE */
  ,{   4,   7,   0,   5,   5, acGUI_FontBNazanin18_0666 } /* code 0666, ARABIC-INDIC DIGIT SIX */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_0667 } /* code 0667, ARABIC-INDIC DIGIT SEVEN */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_0668 } /* code 0668, ARABIC-INDIC DIGIT EIGHT */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_0669 } /* code 0669, ARABIC-INDIC DIGIT NINE */
  ,{   7,   6,   1,   9,   8, acGUI_FontBNazanin18_067E } /* code 067E, ARABIC LETTER PEH */
  ,{   6,   6,   1,   9,   6, acGUI_FontBNazanin18_0686 } /* code 0686, ARABIC LETTER TCHEH */
  ,{   6,   8,  -1,   7,   4, acGUI_FontBNazanin18_0698 } /* code 0698, ARABIC LETTER JEH */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_06A9 } /* code 06A9, ARABIC LETTER KEHEH */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_06AF } /* code 06AF, ARABIC LETTER GAF */
  ,{   3,   6,   1,   6,   4, acGUI_FontBNazanin18_06C0 } /* code 06C0, ARABIC LETTER HEH WITH YEH ABOVE */
  ,{   7,   6,   1,   8,   8, acGUI_FontBNazanin18_06CC } /* code 06CC, ARABIC LETTER FARSI YEH */
  ,{   1,   2,   2,   8,   6, acGUI_FontBNazanin18_06F0 } /* code 06F0, EXTENDED ARABIC-INDIC DIGIT ZERO */
  ,{   2,   7,   2,   5,   6, acGUI_FontBNazanin18_06F1 } /* code 06F1, EXTENDED ARABIC-INDIC DIGIT ONE */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_06F2 } /* code 06F2, EXTENDED ARABIC-INDIC DIGIT TWO */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_06F3 } /* code 06F3, EXTENDED ARABIC-INDIC DIGIT THREE */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_06F4 } /* code 06F4, EXTENDED ARABIC-INDIC DIGIT FOUR */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_06F5 } /* code 06F5, EXTENDED ARABIC-INDIC DIGIT FIVE */
  ,{   4,   7,   0,   5,   5, acGUI_FontBNazanin18_06F6 } /* code 06F6, EXTENDED ARABIC-INDIC DIGIT SIX */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_06F7 } /* code 06F7, EXTENDED ARABIC-INDIC DIGIT SEVEN */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_06F8 } /* code 06F8, EXTENDED ARABIC-INDIC DIGIT EIGHT */
  ,{   4,   7,   1,   5,   6, acGUI_FontBNazanin18_06F9 } /* code 06F9, EXTENDED ARABIC-INDIC DIGIT NINE */
  ,{   1,   1,   0,  12,   0, acGUI_FontBNazanin18_200C } /* code 200C, ZERO WIDTH NON-JOINER */
  ,{   1,   1,   0,  12,   0, acGUI_FontBNazanin18_200D } /* code 200D, ZERO WIDTH JOINER */
  ,{   9,   8,  -1,   4,   0, acGUI_FontBNazanin18_200E } /* code 200E, LEFT-TO-RIGHT MARK */
  ,{   3,   8,  -1,   4,   0, acGUI_FontBNazanin18_200F } /* code 200F, RIGHT-TO-LEFT MARK */
  ,{   2,   4,   0,   3,   3, acGUI_FontBNazanin18_2018 } /* code 2018, LEFT SINGLE QUOTATION MARK */
  ,{   1,   4,   1,   3,   3, acGUI_FontBNazanin18_2019 } /* code 2019, RIGHT SINGLE QUOTATION MARK */
  ,{   3,   3,   0,   4,   4, acGUI_FontBNazanin18_201C } /* code 201C, LEFT DOUBLE QUOTATION MARK */
  ,{   3,   3,   0,   4,   4, acGUI_FontBNazanin18_201D } /* code 201D, RIGHT DOUBLE QUOTATION MARK */
  ,{   2,   5,   0,   6,   3, acGUI_FontBNazanin18_2039 } /* code 2039, SINGLE LEFT-POINTING ANGLE QUOTATION MARK */
  ,{   2,   5,   0,   6,   3, acGUI_FontBNazanin18_203A } /* code 203A, SINGLE RIGHT-POINTING ANGLE QUOTATION MARK */
  ,{   1,   1,   0,   7,   2, acGUI_FontBNazanin18_2219 } /* code 2219, BULLET OPERATOR */
  ,{   2,   4,   0,   1,   0, acGUI_FontBNazanin18_E818 } /* code E818 */
  ,{   2,   2,   0,   6,   0, acGUI_FontBNazanin18_E820 } /* code E820 */
  ,{   2,   2,   0,   5,   0, acGUI_FontBNazanin18_E821 } /* code E821 */
  ,{   1,   1,   1,   6,   0, acGUI_FontBNazanin18_E822 } /* code E822 */
  ,{   1,   3,   0,   5,   0, acGUI_FontBNazanin18_E823 } /* code E823 */
  ,{   2,   2,   0,   5,   0, acGUI_FontBNazanin18_E824 } /* code E824 */
  ,{   2,   2,   0,   6,   0, acGUI_FontBNazanin18_E825 } /* code E825 */
  ,{   2,   2,   0,  14,   0, acGUI_FontBNazanin18_E826 } /* code E826 */
  ,{   2,   2,   0,  14,   0, acGUI_FontBNazanin18_E827 } /* code E827 */
  ,{   2,   4,   0,   4,   0, acGUI_FontBNazanin18_E828 } /* code E828 */
  ,{   2,   3,   0,   4,   0, acGUI_FontBNazanin18_E829 } /* code E829 */
  ,{   2,   4,   0,   3,   0, acGUI_FontBNazanin18_E82A } /* code E82A */
  ,{   2,   4,   0,   3,   0, acGUI_FontBNazanin18_E82B } /* code E82B */
  ,{   2,   3,   0,   4,   0, acGUI_FontBNazanin18_E82C } /* code E82C */
  ,{   2,   4,   0,   3,   0, acGUI_FontBNazanin18_E82D } /* code E82D */
  ,{   7,   6,   1,   9,   8, acGUI_FontBNazanin18_FB56 } /* code FB56, ARABIC LETTER PEH ISOLATED FORM */
  ,{   8,   6,   1,   9,   9, acGUI_FontBNazanin18_FB57 } /* code FB57, ARABIC LETTER PEH FINAL FORM */
  ,{   3,   6,   0,   9,   3, acGUI_FontBNazanin18_FB58 } /* code FB58, ARABIC LETTER PEH INITIAL FORM */
  ,{   4,   5,   0,  10,   4, acGUI_FontBNazanin18_FB59 } /* code FB59, ARABIC LETTER PEH MEDIAL FORM */
  ,{   6,   6,   1,   9,   6, acGUI_FontBNazanin18_FB7A } /* code FB7A, ARABIC LETTER TCHEH ISOLATED FORM */
  ,{   6,   6,   1,   9,   7, acGUI_FontBNazanin18_FB7B } /* code FB7B, ARABIC LETTER TCHEH FINAL FORM */
  ,{   6,   7,   0,   8,   6, acGUI_FontBNazanin18_FB7C } /* code FB7C, ARABIC LETTER TCHEH INITIAL FORM */
  ,{   7,   7,   0,   8,   7, acGUI_FontBNazanin18_FB7D } /* code FB7D, ARABIC LETTER TCHEH MEDIAL FORM */
  ,{   6,   8,  -1,   7,   4, acGUI_FontBNazanin18_FB8A } /* code FB8A, ARABIC LETTER JEH ISOLATED FORM */
  ,{   6,   8,   0,   7,   5, acGUI_FontBNazanin18_FB8B } /* code FB8B, ARABIC LETTER JEH FINAL FORM */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_FB8E } /* code FB8E, ARABIC LETTER KEHEH ISOLATED FORM */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_FB8F } /* code FB8F, ARABIC LETTER KEHEH FINAL FORM */
  ,{   5,   7,   0,   5,   4, acGUI_FontBNazanin18_FB90 } /* code FB90, ARABIC LETTER KEHEH INITIAL FORM */
  ,{   5,   7,   0,   5,   5, acGUI_FontBNazanin18_FB91 } /* code FB91, ARABIC LETTER KEHEH MEDIAL FORM */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_FB92 } /* code FB92, ARABIC LETTER GAF ISOLATED FORM */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_FB93 } /* code FB93, ARABIC LETTER GAF FINAL FORM */
  ,{   5,   7,   0,   5,   4, acGUI_FontBNazanin18_FB94 } /* code FB94, ARABIC LETTER GAF INITIAL FORM */
  ,{   5,   7,   0,   5,   5, acGUI_FontBNazanin18_FB95 } /* code FB95, ARABIC LETTER GAF MEDIAL FORM */
  ,{   3,   6,   1,   6,   4, acGUI_FontBNazanin18_FBA4 } /* code FBA4, ARABIC LETTER HEH WITH YEH ABOVE ISOLATED FORM */
  ,{   4,   7,   1,   5,   5, acGUI_FontBNazanin18_FBA5 } /* code FBA5, ARABIC LETTER HEH WITH YEH ABOVE FINAL FORM */
  ,{   7,   6,   1,   8,   8, acGUI_FontBNazanin18_FBFC } /* code FBFC, ARABIC LETTER FARSI YEH ISOLATED FORM */
  ,{   7,   4,   1,  11,   7, acGUI_FontBNazanin18_FBFD } /* code FBFD, ARABIC LETTER FARSI YEH FINAL FORM */
  ,{   3,   5,   0,   9,   3, acGUI_FontBNazanin18_FBFE } /* code FBFE, ARABIC LETTER FARSI YEH INITIAL FORM */
  ,{   4,   4,   0,  10,   4, acGUI_FontBNazanin18_FBFF } /* code FBFF, ARABIC LETTER FARSI YEH MEDIAL FORM */
  ,{   2,   4,   0,   1,   0, acGUI_FontBNazanin18_FC5E } /* code FC5E, ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM */
  ,{   2,   4,   0,   1,   0, acGUI_FontBNazanin18_FC5F } /* code FC5F, ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM */
  ,{   2,   4,   0,   2,   0, acGUI_FontBNazanin18_FC60 } /* code FC60, ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM */
  ,{   2,   3,   0,   2,   0, acGUI_FontBNazanin18_FC61 } /* code FC61, ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM */
  ,{   2,   3,   0,   2,   0, acGUI_FontBNazanin18_FC62 } /* code FC62, ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM */
  ,{   7,   8,   1,   4,   8, acGUI_FontBNazanin18_FDF2 } /* code FDF2, ARABIC LIGATURE ALLAH ISOLATED FORM */
  ,{   2,   8,   0,   4,   3, acGUI_FontBNazanin18_FE81 } /* code FE81, ARABIC LETTER ALEF WITH MADDA ABOVE ISOLATED FORM */
  ,{   3,   8,   0,   4,   4, acGUI_FontBNazanin18_FE82 } /* code FE82, ARABIC LETTER ALEF WITH MADDA ABOVE FINAL FORM */
  ,{   2,   9,   1,   3,   3, acGUI_FontBNazanin18_FE83 } /* code FE83, ARABIC LETTER ALEF WITH HAMZA ABOVE ISOLATED FORM */
  ,{   3,   9,   1,   3,   3, acGUI_FontBNazanin18_FE84 } /* code FE84, ARABIC LETTER ALEF WITH HAMZA ABOVE FINAL FORM */
  ,{   3,   9,   0,   6,   4, acGUI_FontBNazanin18_FE85 } /* code FE85, ARABIC LETTER WAW WITH HAMZA ABOVE ISOLATED FORM */
  ,{   4,   9,   0,   6,   5, acGUI_FontBNazanin18_FE86 } /* code FE86, ARABIC LETTER WAW WITH HAMZA ABOVE FINAL FORM */
  ,{   2,  10,   1,   5,   3, acGUI_FontBNazanin18_FE87 } /* code FE87, ARABIC LETTER ALEF WITH HAMZA BELOW ISOLATED FORM */
  ,{   2,  10,   1,   5,   3, acGUI_FontBNazanin18_FE88 } /* code FE88, ARABIC LETTER ALEF WITH HAMZA BELOW FINAL FORM */
  ,{   7,   6,   1,   8,   8, acGUI_FontBNazanin18_FE89 } /* code FE89, ARABIC LETTER YEH WITH HAMZA ABOVE ISOLATED FORM */
  ,{   7,   7,   1,   8,   7, acGUI_FontBNazanin18_FE8A } /* code FE8A, ARABIC LETTER YEH WITH HAMZA ABOVE FINAL FORM */
  ,{   2,   6,   0,   6,   2, acGUI_FontBNazanin18_FE8B } /* code FE8B, ARABIC LETTER YEH WITH HAMZA ABOVE INITIAL FORM */
  ,{   4,   5,   0,   7,   4, acGUI_FontBNazanin18_FE8C } /* code FE8C, ARABIC LETTER YEH WITH HAMZA ABOVE MEDIAL FORM */
  ,{   1,   7,   1,   5,   2, acGUI_FontBNazanin18_FE8D } /* code FE8D, ARABIC LETTER ALEF ISOLATED FORM */
  ,{   2,   7,   1,   5,   3, acGUI_FontBNazanin18_FE8E } /* code FE8E, ARABIC LETTER ALEF FINAL FORM */
  ,{   7,   5,   1,   9,   8, acGUI_FontBNazanin18_FE8F } /* code FE8F, ARABIC LETTER BEH ISOLATED FORM */
  ,{   8,   5,   1,   9,   9, acGUI_FontBNazanin18_FE90 } /* code FE90, ARABIC LETTER BEH FINAL FORM */
  ,{   2,   5,   0,   9,   2, acGUI_FontBNazanin18_FE91 } /* code FE91, ARABIC LETTER BEH INITIAL FORM */
  ,{   4,   4,   0,  10,   4, acGUI_FontBNazanin18_FE92 } /* code FE92, ARABIC LETTER BEH MEDIAL FORM */
  ,{   3,   6,   1,   6,   4, acGUI_FontBNazanin18_FE93 } /* code FE93, ARABIC LETTER TEH MARBUTA ISOLATED FORM */
  ,{   4,   7,   1,   5,   5, acGUI_FontBNazanin18_FE94 } /* code FE94, ARABIC LETTER TEH MARBUTA FINAL FORM */
  ,{   7,   5,   1,   7,   8, acGUI_FontBNazanin18_FE95 } /* code FE95, ARABIC LETTER TEH ISOLATED FORM */
  ,{   8,   5,   1,   7,   9, acGUI_FontBNazanin18_FE96 } /* code FE96, ARABIC LETTER TEH FINAL FORM */
  ,{   5,   5,  -1,   7,   3, acGUI_FontBNazanin18_FE97 } /* code FE97, ARABIC LETTER TEH INITIAL FORM */
  ,{   4,   5,   0,   7,   4, acGUI_FontBNazanin18_FE98 } /* code FE98, ARABIC LETTER TEH MEDIAL FORM */
  ,{   9,   5,   0,   7,   8, acGUI_FontBNazanin18_FE99 } /* code FE99, ARABIC LETTER THEH ISOLATED FORM */
  ,{   9,   5,   0,   7,   9, acGUI_FontBNazanin18_FE9A } /* code FE9A, ARABIC LETTER THEH FINAL FORM */
  ,{   3,   6,   0,   6,   3, acGUI_FontBNazanin18_FE9B } /* code FE9B, ARABIC LETTER THEH INITIAL FORM */
  ,{   9,   5,  -3,   7,   4, acGUI_FontBNazanin18_FE9C } /* code FE9C, ARABIC LETTER THEH MEDIAL FORM */
  ,{   6,   6,   1,   9,   6, acGUI_FontBNazanin18_FE9D } /* code FE9D, ARABIC LETTER JEEM ISOLATED FORM */
  ,{   6,   6,   1,   9,   7, acGUI_FontBNazanin18_FE9E } /* code FE9E, ARABIC LETTER JEEM FINAL FORM */
  ,{   6,   6,   0,   8,   6, acGUI_FontBNazanin18_FE9F } /* code FE9F, ARABIC LETTER JEEM INITIAL FORM */
  ,{   7,   6,   0,   8,   7, acGUI_FontBNazanin18_FEA0 } /* code FEA0, ARABIC LETTER JEEM MEDIAL FORM */
  ,{   6,   6,   1,   9,   6, acGUI_FontBNazanin18_FEA1 } /* code FEA1, ARABIC LETTER HAH ISOLATED FORM */
  ,{   6,   6,   1,   9,   7, acGUI_FontBNazanin18_FEA2 } /* code FEA2, ARABIC LETTER HAH FINAL FORM */
  ,{   6,   4,   0,   8,   6, acGUI_FontBNazanin18_FEA3 } /* code FEA3, ARABIC LETTER HAH INITIAL FORM */
  ,{   7,   4,   0,   8,   7, acGUI_FontBNazanin18_FEA4 } /* code FEA4, ARABIC LETTER HAH MEDIAL FORM */
  ,{   6,   9,   1,   6,   6, acGUI_FontBNazanin18_FEA5 } /* code FEA5, ARABIC LETTER KHAH ISOLATED FORM */
  ,{   6,   9,   1,   6,   7, acGUI_FontBNazanin18_FEA6 } /* code FEA6, ARABIC LETTER KHAH FINAL FORM */
  ,{   6,   6,   0,   6,   6, acGUI_FontBNazanin18_FEA7 } /* code FEA7, ARABIC LETTER KHAH INITIAL FORM */
  ,{   7,   6,   0,   6,   7, acGUI_FontBNazanin18_FEA8 } /* code FEA8, ARABIC LETTER KHAH MEDIAL FORM */
  ,{   4,   4,   1,   8,   5, acGUI_FontBNazanin18_FEA9 } /* code FEA9, ARABIC LETTER DAL ISOLATED FORM */
  ,{   5,   5,   1,   7,   6, acGUI_FontBNazanin18_FEAA } /* code FEAA, ARABIC LETTER DAL FINAL FORM */
  ,{   4,   7,   1,   5,   5, acGUI_FontBNazanin18_FEAB } /* code FEAB, ARABIC LETTER THAL ISOLATED FORM */
  ,{   5,   7,   1,   5,   6, acGUI_FontBNazanin18_FEAC } /* code FEAC, ARABIC LETTER THAL FINAL FORM */
  ,{   3,   5,   0,  10,   4, acGUI_FontBNazanin18_FEAD } /* code FEAD, ARABIC LETTER REH ISOLATED FORM */
  ,{   3,   5,   1,  10,   5, acGUI_FontBNazanin18_FEAE } /* code FEAE, ARABIC LETTER REH FINAL FORM */
  ,{   3,   8,   0,   7,   4, acGUI_FontBNazanin18_FEAF } /* code FEAF, ARABIC LETTER ZAIN ISOLATED FORM */
  ,{   3,   8,   1,   7,   5, acGUI_FontBNazanin18_FEB0 } /* code FEB0, ARABIC LETTER ZAIN FINAL FORM */
  ,{  10,   6,   1,   9,  10, acGUI_FontBNazanin18_FEB1 } /* code FEB1, ARABIC LETTER SEEN ISOLATED FORM */
  ,{  11,   5,   1,  10,  11, acGUI_FontBNazanin18_FEB2 } /* code FEB2, ARABIC LETTER SEEN FINAL FORM */
  ,{   6,   3,   0,   9,   6, acGUI_FontBNazanin18_FEB3 } /* code FEB3, ARABIC LETTER SEEN INITIAL FORM */
  ,{   7,   2,   0,  10,   7, acGUI_FontBNazanin18_FEB4 } /* code FEB4, ARABIC LETTER SEEN MEDIAL FORM */
  ,{  10,   9,   1,   6,  10, acGUI_FontBNazanin18_FEB5 } /* code FEB5, ARABIC LETTER SHEEN ISOLATED FORM */
  ,{  11,   9,   1,   6,  11, acGUI_FontBNazanin18_FEB6 } /* code FEB6, ARABIC LETTER SHEEN FINAL FORM */
  ,{   6,   6,   0,   6,   6, acGUI_FontBNazanin18_FEB7 } /* code FEB7, ARABIC LETTER SHEEN INITIAL FORM */
  ,{   7,   6,   0,   6,   7, acGUI_FontBNazanin18_FEB8 } /* code FEB8, ARABIC LETTER SHEEN MEDIAL FORM */
  ,{  10,   6,   1,   9,  11, acGUI_FontBNazanin18_FEB9 } /* code FEB9, ARABIC LETTER SAD ISOLATED FORM */
  ,{  11,   6,   1,   9,  12, acGUI_FontBNazanin18_FEBA } /* code FEBA, ARABIC LETTER SAD FINAL FORM */
  ,{   7,   3,   0,   9,   7, acGUI_FontBNazanin18_FEBB } /* code FEBB, ARABIC LETTER SAD INITIAL FORM */
  ,{   7,   3,   0,   9,   7, acGUI_FontBNazanin18_FEBC } /* code FEBC, ARABIC LETTER SAD MEDIAL FORM */
  ,{  10,   9,   1,   6,  11, acGUI_FontBNazanin18_FEBD } /* code FEBD, ARABIC LETTER DAD ISOLATED FORM */
  ,{  11,   9,   1,   6,  12, acGUI_FontBNazanin18_FEBE } /* code FEBE, ARABIC LETTER DAD FINAL FORM */
  ,{   7,   6,   0,   6,   7, acGUI_FontBNazanin18_FEBF } /* code FEBF, ARABIC LETTER DAD INITIAL FORM */
  ,{   7,   6,   0,   6,   7, acGUI_FontBNazanin18_FEC0 } /* code FEC0, ARABIC LETTER DAD MEDIAL FORM */
  ,{   7,   7,   1,   5,   8, acGUI_FontBNazanin18_FEC1 } /* code FEC1, ARABIC LETTER TAH ISOLATED FORM */
  ,{   8,   7,   1,   5,   8, acGUI_FontBNazanin18_FEC2 } /* code FEC2, ARABIC LETTER TAH FINAL FORM */
  ,{   6,   7,   0,   5,   6, acGUI_FontBNazanin18_FEC3 } /* code FEC3, ARABIC LETTER TAH INITIAL FORM */
  ,{   7,   7,   0,   5,   6, acGUI_FontBNazanin18_FEC4 } /* code FEC4, ARABIC LETTER TAH MEDIAL FORM */
  ,{   7,   7,   1,   5,   8, acGUI_FontBNazanin18_FEC5 } /* code FEC5, ARABIC LETTER ZAH ISOLATED FORM */
  ,{   8,   7,   1,   5,   8, acGUI_FontBNazanin18_FEC6 } /* code FEC6, ARABIC LETTER ZAH FINAL FORM */
  ,{   6,   7,   0,   5,   6, acGUI_FontBNazanin18_FEC7 } /* code FEC7, ARABIC LETTER ZAH INITIAL FORM */
  ,{   7,   7,   0,   5,   6, acGUI_FontBNazanin18_FEC8 } /* code FEC8, ARABIC LETTER ZAH MEDIAL FORM */
  ,{   5,   7,   1,   8,   5, acGUI_FontBNazanin18_FEC9 } /* code FEC9, ARABIC LETTER AIN ISOLATED FORM */
  ,{   5,   6,   1,   9,   6, acGUI_FontBNazanin18_FECA } /* code FECA, ARABIC LETTER AIN FINAL FORM */
  ,{   4,   4,   0,   8,   4, acGUI_FontBNazanin18_FECB } /* code FECB, ARABIC LETTER AIN INITIAL FORM */
  ,{   5,   3,   0,   9,   4, acGUI_FontBNazanin18_FECC } /* code FECC, ARABIC LETTER AIN MEDIAL FORM */
  ,{   5,  10,   1,   5,   5, acGUI_FontBNazanin18_FECD } /* code FECD, ARABIC LETTER GHAIN ISOLATED FORM */
  ,{   5,   9,   1,   6,   6, acGUI_FontBNazanin18_FECE } /* code FECE, ARABIC LETTER GHAIN FINAL FORM */
  ,{   4,   7,   0,   5,   4, acGUI_FontBNazanin18_FECF } /* code FECF, ARABIC LETTER GHAIN INITIAL FORM */
  ,{   5,   6,   0,   6,   4, acGUI_FontBNazanin18_FED0 } /* code FED0, ARABIC LETTER GHAIN MEDIAL FORM */
  ,{   7,   7,   1,   5,   8, acGUI_FontBNazanin18_FED1 } /* code FED1, ARABIC LETTER FEH ISOLATED FORM */
  ,{   8,   6,   1,   6,   9, acGUI_FontBNazanin18_FED2 } /* code FED2, ARABIC LETTER FEH FINAL FORM */
  ,{   3,   7,   0,   5,   3, acGUI_FontBNazanin18_FED3 } /* code FED3, ARABIC LETTER FEH INITIAL FORM */
  ,{   4,   6,   0,   6,   4, acGUI_FontBNazanin18_FED4 } /* code FED4, ARABIC LETTER FEH MEDIAL FORM */
  ,{   6,   8,   1,   7,   7, acGUI_FontBNazanin18_FED5 } /* code FED5, ARABIC LETTER QAF ISOLATED FORM */
  ,{   6,   8,   1,   7,   7, acGUI_FontBNazanin18_FED6 } /* code FED6, ARABIC LETTER QAF FINAL FORM */
  ,{   3,   7,   0,   5,   3, acGUI_FontBNazanin18_FED7 } /* code FED7, ARABIC LETTER QAF INITIAL FORM */
  ,{   4,   6,   0,   6,   4, acGUI_FontBNazanin18_FED8 } /* code FED8, ARABIC LETTER QAF MEDIAL FORM */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_FED9 } /* code FED9, ARABIC LETTER KAF ISOLATED FORM */
  ,{   9,   7,   1,   5,  10, acGUI_FontBNazanin18_FEDA } /* code FEDA, ARABIC LETTER KAF FINAL FORM */
  ,{   5,   7,   0,   5,   4, acGUI_FontBNazanin18_FEDB } /* code FEDB, ARABIC LETTER KAF INITIAL FORM */
  ,{   5,   7,   0,   5,   5, acGUI_FontBNazanin18_FEDC } /* code FEDC, ARABIC LETTER KAF MEDIAL FORM */
  ,{   6,  10,   1,   5,   6, acGUI_FontBNazanin18_FEDD } /* code FEDD, ARABIC LETTER LAM ISOLATED FORM */
  ,{   5,  10,   1,   5,   7, acGUI_FontBNazanin18_FEDE } /* code FEDE, ARABIC LETTER LAM FINAL FORM */
  ,{   2,   7,   0,   5,   2, acGUI_FontBNazanin18_FEDF } /* code FEDF, ARABIC LETTER LAM INITIAL FORM */
  ,{   3,   7,   0,   5,   3, acGUI_FontBNazanin18_FEE0 } /* code FEE0, ARABIC LETTER LAM MEDIAL FORM */
  ,{   4,   6,   1,   9,   5, acGUI_FontBNazanin18_FEE1 } /* code FEE1, ARABIC LETTER MEEM ISOLATED FORM */
  ,{   5,   5,   1,  10,   6, acGUI_FontBNazanin18_FEE2 } /* code FEE2, ARABIC LETTER MEEM FINAL FORM */
  ,{   4,   3,   0,   9,   4, acGUI_FontBNazanin18_FEE3 } /* code FEE3, ARABIC LETTER MEEM INITIAL FORM */
  ,{   6,   3,   0,   9,   5, acGUI_FontBNazanin18_FEE4 } /* code FEE4, ARABIC LETTER MEEM MEDIAL FORM */
  ,{   6,   7,   1,   8,   7, acGUI_FontBNazanin18_FEE5 } /* code FEE5, ARABIC LETTER NOON ISOLATED FORM */
  ,{   7,   7,   1,   8,   7, acGUI_FontBNazanin18_FEE6 } /* code FEE6, ARABIC LETTER NOON FINAL FORM */
  ,{   2,   6,   0,   6,   2, acGUI_FontBNazanin18_FEE7 } /* code FEE7, ARABIC LETTER NOON INITIAL FORM */
  ,{   5,   4,  -1,   8,   4, acGUI_FontBNazanin18_FEE8 } /* code FEE8, ARABIC LETTER NOON MEDIAL FORM */
  ,{   3,   3,   1,   9,   4, acGUI_FontBNazanin18_FEE9 } /* code FEE9, ARABIC LETTER HEH ISOLATED FORM */
  ,{   4,   5,   1,   7,   5, acGUI_FontBNazanin18_FEEA } /* code FEEA, ARABIC LETTER HEH FINAL FORM */
  ,{   5,   4,   0,   8,   5, acGUI_FontBNazanin18_FEEB } /* code FEEB, ARABIC LETTER HEH INITIAL FORM */
  ,{   5,   7,   0,   8,   5, acGUI_FontBNazanin18_FEEC } /* code FEEC, ARABIC LETTER HEH MEDIAL FORM */
  ,{   3,   6,   0,   9,   4, acGUI_FontBNazanin18_FEED } /* code FEED, ARABIC LETTER WAW ISOLATED FORM */
  ,{   4,   6,   0,   9,   5, acGUI_FontBNazanin18_FEEE } /* code FEEE, ARABIC LETTER WAW FINAL FORM */
  ,{   7,   6,   1,   8,   8, acGUI_FontBNazanin18_FEEF } /* code FEEF, ARABIC LETTER ALEF MAKSURA ISOLATED FORM */
  ,{   7,   4,   1,  11,   7, acGUI_FontBNazanin18_FEF0 } /* code FEF0, ARABIC LETTER ALEF MAKSURA FINAL FORM */
  ,{   7,   6,   1,   8,   8, acGUI_FontBNazanin18_FEF1 } /* code FEF1, ARABIC LETTER YEH ISOLATED FORM */
  ,{   7,   4,   1,  11,   7, acGUI_FontBNazanin18_FEF2 } /* code FEF2, ARABIC LETTER YEH FINAL FORM */
  ,{   3,   5,   0,   9,   3, acGUI_FontBNazanin18_FEF3 } /* code FEF3, ARABIC LETTER YEH INITIAL FORM */
  ,{   4,   4,   0,  10,   4, acGUI_FontBNazanin18_FEF4 } /* code FEF4, ARABIC LETTER YEH MEDIAL FORM */
  ,{   6,   8,   0,   4,   6, acGUI_FontBNazanin18_FEF5 } /* code FEF5, ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM */
  ,{   6,   9,   0,   4,   7, acGUI_FontBNazanin18_FEF6 } /* code FEF6, ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM */
  ,{   6,   9,   0,   3,   6, acGUI_FontBNazanin18_FEF7 } /* code FEF7, ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM */
  ,{   6,  10,   0,   3,   7, acGUI_FontBNazanin18_FEF8 } /* code FEF8, ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM */
  ,{   5,  10,   0,   5,   6, acGUI_FontBNazanin18_FEF9 } /* code FEF9, ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW ISOLATED FORM */
  ,{   5,  10,   1,   5,   7, acGUI_FontBNazanin18_FEFA } /* code FEFA, ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW FINAL FORM */
  ,{   5,   7,   0,   5,   6, acGUI_FontBNazanin18_FEFB } /* code FEFB, ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM */
  ,{   5,   8,   1,   5,   7, acGUI_FontBNazanin18_FEFC } /* code FEFC, ARABIC LIGATURE LAM WITH ALEF FINAL FORM */
  ,{   5,   8,   1,   4,   6, acGUI_FontBNazanin18_FFFF } /* code FFFF */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop45 = {
   0xFFFF /* first character */
  ,0xFFFF /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[288] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop44 = {
   0xFE81 /* first character */
  ,0xFEFC /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[164] /* address of first character */
  ,&GUI_FontBNazanin18_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop43 = {
   0xFDF2 /* first character */
  ,0xFDF2 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[163] /* address of first character */
  ,&GUI_FontBNazanin18_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop42 = {
   0xFC5E /* first character */
  ,0xFC62 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[158] /* address of first character */
  ,&GUI_FontBNazanin18_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop41 = {
   0xFBFC /* first character */
  ,0xFBFF /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[154] /* address of first character */
  ,&GUI_FontBNazanin18_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop40 = {
   0xFBA4 /* first character */
  ,0xFBA5 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[152] /* address of first character */
  ,&GUI_FontBNazanin18_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop39 = {
   0xFB8E /* first character */
  ,0xFB95 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[144] /* address of first character */
  ,&GUI_FontBNazanin18_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop38 = {
   0xFB8A /* first character */
  ,0xFB8B /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[142] /* address of first character */
  ,&GUI_FontBNazanin18_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop37 = {
   0xFB7A /* first character */
  ,0xFB7D /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[138] /* address of first character */
  ,&GUI_FontBNazanin18_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop36 = {
   0xFB56 /* first character */
  ,0xFB59 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[134] /* address of first character */
  ,&GUI_FontBNazanin18_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop35 = {
   0xE820 /* first character */
  ,0xE82D /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[120] /* address of first character */
  ,&GUI_FontBNazanin18_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop34 = {
   0xE818 /* first character */
  ,0xE818 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[119] /* address of first character */
  ,&GUI_FontBNazanin18_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop33 = {
   0x2219 /* first character */
  ,0x2219 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[118] /* address of first character */
  ,&GUI_FontBNazanin18_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop32 = {
   0x2039 /* first character */
  ,0x203A /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[116] /* address of first character */
  ,&GUI_FontBNazanin18_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop31 = {
   0x201C /* first character */
  ,0x201D /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[114] /* address of first character */
  ,&GUI_FontBNazanin18_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop30 = {
   0x2018 /* first character */
  ,0x2019 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[112] /* address of first character */
  ,&GUI_FontBNazanin18_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop29 = {
   0x200C /* first character */
  ,0x200F /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[108] /* address of first character */
  ,&GUI_FontBNazanin18_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop28 = {
   0x06F0 /* first character */
  ,0x06F9 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 98] /* address of first character */
  ,&GUI_FontBNazanin18_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop27 = {
   0x06CC /* first character */
  ,0x06CC /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 97] /* address of first character */
  ,&GUI_FontBNazanin18_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop26 = {
   0x06C0 /* first character */
  ,0x06C0 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 96] /* address of first character */
  ,&GUI_FontBNazanin18_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop25 = {
   0x06AF /* first character */
  ,0x06AF /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 95] /* address of first character */
  ,&GUI_FontBNazanin18_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop24 = {
   0x06A9 /* first character */
  ,0x06A9 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 94] /* address of first character */
  ,&GUI_FontBNazanin18_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop23 = {
   0x0698 /* first character */
  ,0x0698 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 93] /* address of first character */
  ,&GUI_FontBNazanin18_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop22 = {
   0x0686 /* first character */
  ,0x0686 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 92] /* address of first character */
  ,&GUI_FontBNazanin18_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop21 = {
   0x067E /* first character */
  ,0x067E /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 91] /* address of first character */
  ,&GUI_FontBNazanin18_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop20 = {
   0x0660 /* first character */
  ,0x0669 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 81] /* address of first character */
  ,&GUI_FontBNazanin18_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop19 = {
   0x0640 /* first character */
  ,0x0652 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 62] /* address of first character */
  ,&GUI_FontBNazanin18_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop18 = {
   0x0621 /* first character */
  ,0x063A /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 36] /* address of first character */
  ,&GUI_FontBNazanin18_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop17 = {
   0x061F /* first character */
  ,0x061F /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 35] /* address of first character */
  ,&GUI_FontBNazanin18_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop16 = {
   0x061B /* first character */
  ,0x061B /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 34] /* address of first character */
  ,&GUI_FontBNazanin18_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop15 = {
   0x060C /* first character */
  ,0x060C /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 33] /* address of first character */
  ,&GUI_FontBNazanin18_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop14 = {
   0x02D9 /* first character */
  ,0x02D9 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 32] /* address of first character */
  ,&GUI_FontBNazanin18_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop13 = {
   0x00F7 /* first character */
  ,0x00F7 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 31] /* address of first character */
  ,&GUI_FontBNazanin18_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop12 = {
   0x00D7 /* first character */
  ,0x00D7 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 30] /* address of first character */
  ,&GUI_FontBNazanin18_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop11 = {
   0x00BB /* first character */
  ,0x00BB /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 29] /* address of first character */
  ,&GUI_FontBNazanin18_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop10 = {
   0x00B7 /* first character */
  ,0x00B7 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 28] /* address of first character */
  ,&GUI_FontBNazanin18_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop9 = {
   0x00AB /* first character */
  ,0x00AB /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 27] /* address of first character */
  ,&GUI_FontBNazanin18_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop8 = {
   0x007D /* first character */
  ,0x007D /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 26] /* address of first character */
  ,&GUI_FontBNazanin18_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop7 = {
   0x007B /* first character */
  ,0x007B /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 25] /* address of first character */
  ,&GUI_FontBNazanin18_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop6 = {
   0x005D /* first character */
  ,0x005D /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 24] /* address of first character */
  ,&GUI_FontBNazanin18_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop5 = {
   0x005B /* first character */
  ,0x005B /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 23] /* address of first character */
  ,&GUI_FontBNazanin18_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop4 = {
   0x003D /* first character */
  ,0x003D /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[ 22] /* address of first character */
  ,&GUI_FontBNazanin18_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop3 = {
   0x0028 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[  3] /* address of first character */
  ,&GUI_FontBNazanin18_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[  2] /* address of first character */
  ,&GUI_FontBNazanin18_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontBNazanin18_Prop1 = {
   0x0020 /* first character */
  ,0x0021 /* last character  */
  ,&GUI_FontBNazanin18_CharInfo[  0] /* address of first character */
  ,&GUI_FontBNazanin18_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontBNazanin18 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,18 /* height of font  */
  ,18 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontBNazanin18_Prop1}
  ,12 /* Baseline */
  ,0 /* Height of lowercase characters */
  ,0 /* Height of capital characters */
};

